### ISSUE TITLE
error on npm start

### ISSUE THREAD

**Issue by marwicha** [prvnbist/expense-app-backend#4]
![Capture](https://user-images.githubusercontent.com/11017255/63939161-e80aaf00-ca66-11e9-9011-39a8d2a334e9.PNG)

**Comment by prvnbist** [comment]
Use `npm run dev` command to run the dev server. The `npm start` command is for running the app in production.

**Comment by prvnbist** [comment]
Due to inactivity, I'll be closing this. Feel free to reopen it or create a new issue in the future.
